name: www2.freezone.ourworld.tf
on:
  push:
    branches: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.freezone.ourworld.tf
      uses: appleboy/ssh-action@master
      with:
        host: www2.freezone.ourworld.tf
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www2/www_ourworld_freezone/
          git log -1
          git fetch
          git reset --hard origin/development
          sed -i "s/https:\/\/freezone.ourworld.tf/https:\/\/www2.freezone.ourworld.tf/g" config.toml
          ./build.sh
